// This workflow was automatically generated by the operandi_utils.oton module
nextflow.enable.dsl = 2

params.input_file_group = "OCR-D-IMG"
params.mets_path = "null"
params.workspace_dir = "null"
params.pages = "null"
params.mets_socket_path = "null"
params.cpus = "null"
params.ram = "null"
params.forks = params.cpus
params.cpus_per_fork = (params.cpus.toInteger() / params.forks.toInteger()).intValue()
params.ram_per_fork = sprintf("%dGB", (params.ram.toInteger() / params.forks.toInteger()).intValue())
params.env_wrapper_cmd_core = "null"
params.env_wrapper_cmd_step0 = "null"
params.env_wrapper_cmd_step1 = "null"
params.env_wrapper_cmd_step2 = "null"
params.env_wrapper_cmd_step3 = "null"
params.env_wrapper_cmd_step4 = "null"
params.env_wrapper_cmd_step5 = "null"
params.env_wrapper_cmd_step6 = "null"
params.env_wrapper_cmd_step7 = "null"
params.env_wrapper_cmd_step8 = "null"
params.env_wrapper_cmd_step9 = "null"

log.info """\
    OPERANDI HPC - Nextflow Workflow
    ===================================================
    input_file_group: ${params.input_file_group}
    mets_path: ${params.mets_path}
    workspace_dir: ${params.workspace_dir}
    pages: ${params.pages}
    mets_socket_path: ${params.mets_socket_path}
    cpus: ${params.cpus}
    ram: ${params.ram}
    forks: ${params.forks}
    cpus_per_fork: ${params.cpus_per_fork}
    ram_per_fork: ${params.ram_per_fork}
    env_wrapper_cmd_core: ${params.env_wrapper_cmd_core}
    env_wrapper_cmd_step0: ${params.env_wrapper_cmd_step0}
    env_wrapper_cmd_step1: ${params.env_wrapper_cmd_step1}
    env_wrapper_cmd_step2: ${params.env_wrapper_cmd_step2}
    env_wrapper_cmd_step3: ${params.env_wrapper_cmd_step3}
    env_wrapper_cmd_step4: ${params.env_wrapper_cmd_step4}
    env_wrapper_cmd_step5: ${params.env_wrapper_cmd_step5}
    env_wrapper_cmd_step6: ${params.env_wrapper_cmd_step6}
    env_wrapper_cmd_step7: ${params.env_wrapper_cmd_step7}
    env_wrapper_cmd_step8: ${params.env_wrapper_cmd_step8}
    env_wrapper_cmd_step9: ${params.env_wrapper_cmd_step9}
    """.stripIndent()

process split_page_ranges {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val range_multiplier

    output:
        env mets_file_chunk
        env current_range_pages

    script:
        """
        current_range_pages=\$(${params.env_wrapper_cmd_core} ocrd workspace -d ${params.workspace_dir} list-page -f comma-separated -D ${params.forks} -C ${range_multiplier})
        echo "Current range is: \$current_range_pages"
        mets_file_chunk=\$(echo ${params.mets_path})
        """
}

process ocrd_cis_ocropy_binarize_0 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step0} ocrd-cis-ocropy-binarize -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"dpi": 300}'
        """
}

process ocrd_anybaseocr_crop_1 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step1} ocrd-anybaseocr-crop -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"dpi": 300}'
        """
}

process ocrd_cis_ocropy_denoise_2 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step2} ocrd-cis-ocropy-denoise -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"dpi": 300}'
        """
}

process ocrd_cis_ocropy_deskew_3 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step3} ocrd-cis-ocropy-deskew -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"level-of-operation": "page"}'
        """
}

process ocrd_tesserocr_segment_region_4 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step4} ocrd-tesserocr-segment-region -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"padding": 5.0, "find_tables": false, "dpi": 300}'
        """
}

process ocrd_segment_repair_5 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step5} ocrd-segment-repair -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"plausibilize": true, "plausibilize_merge_min_overlap": 0.7}'
        """
}

process ocrd_cis_ocropy_clip_6 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step6} ocrd-cis-ocropy-clip -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group}
        """
}

process ocrd_cis_ocropy_segment_7 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step7} ocrd-cis-ocropy-segment -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"dpi": 300}'
        """
}

process ocrd_cis_ocropy_dewarp_8 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step8} ocrd-cis-ocropy-dewarp -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group}
        """
}

process ocrd_tesserocr_recognize_9 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val input_group
        val output_group

    output:
        val mets_path
        val page_range

    script:
        """
        ${params.env_wrapper_cmd_step9} ocrd-tesserocr-recognize -U ${params.mets_socket_path} -w ${params.workspace_dir} -m ${mets_path} --page-id ${page_range} -I ${input_group} -O ${output_group} -p '{"model": "Fraktur"}'
        """
}

workflow {
    main:
        ch_range_multipliers = Channel.of(0..params.forks.intValue()-1)
        split_page_ranges(ch_range_multipliers)
        ocrd_cis_ocropy_binarize_0(split_page_ranges.out[0], split_page_ranges.out[1], params.input_file_group, "OCR-D-BINPAGE")
        ocrd_anybaseocr_crop_1(ocrd_cis_ocropy_binarize_0.out[0], ocrd_cis_ocropy_binarize_0.out[1], "OCR-D-BINPAGE", "OCR-D-SEG-PAGE-ANYOCR")
        ocrd_cis_ocropy_denoise_2(ocrd_anybaseocr_crop_1.out[0], ocrd_anybaseocr_crop_1.out[1], "OCR-D-SEG-PAGE-ANYOCR", "OCR-D-DENOISE-OCROPY")
        ocrd_cis_ocropy_deskew_3(ocrd_cis_ocropy_denoise_2.out[0], ocrd_cis_ocropy_denoise_2.out[1], "OCR-D-DENOISE-OCROPY", "OCR-D-DESKEW-OCROPY")
        ocrd_tesserocr_segment_region_4(ocrd_cis_ocropy_deskew_3.out[0], ocrd_cis_ocropy_deskew_3.out[1], "OCR-D-DESKEW-OCROPY", "OCR-D-SEG-BLOCK-TESSERACT")
        ocrd_segment_repair_5(ocrd_tesserocr_segment_region_4.out[0], ocrd_tesserocr_segment_region_4.out[1], "OCR-D-SEG-BLOCK-TESSERACT", "OCR-D-SEGMENT-REPAIR")
        ocrd_cis_ocropy_clip_6(ocrd_segment_repair_5.out[0], ocrd_segment_repair_5.out[1], "OCR-D-SEGMENT-REPAIR", "OCR-D-CLIP")
        ocrd_cis_ocropy_segment_7(ocrd_cis_ocropy_clip_6.out[0], ocrd_cis_ocropy_clip_6.out[1], "OCR-D-CLIP", "OCR-D-SEGMENT-OCROPY")
        ocrd_cis_ocropy_dewarp_8(ocrd_cis_ocropy_segment_7.out[0], ocrd_cis_ocropy_segment_7.out[1], "OCR-D-SEGMENT-OCROPY", "OCR-D-DEWARP")
        ocrd_tesserocr_recognize_9(ocrd_cis_ocropy_dewarp_8.out[0], ocrd_cis_ocropy_dewarp_8.out[1], "OCR-D-DEWARP", "OCR-D-OCR")
}
