// This workflow was automatically generated by the v2.17.0 operandi_utils.oton module
nextflow.enable.dsl = 2

params.input_file_group = "OCR-D-IMG"
params.mets_path = "null"
params.workspace_dir = "null"
params.pages = "null"
params.mets_socket_path = "null"
params.cpus = "null"
params.ram = "null"
params.forks = params.cpus
params.cpus_per_fork = (params.cpus.toInteger() / params.forks.toInteger()).intValue()
params.ram_per_fork = sprintf("%dGB", (params.ram.toInteger() / params.forks.toInteger()).intValue())
params.env_wrapper_cmd = "null"

process split_page_ranges {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val range_multiplier

    output:
        env current_range_pages

    script:
        """
        current_range_pages=\$(${params.env_wrapper_cmd} ocrd workspace -d ${params.workspace_dir} list-page -f comma-separated -D ${params.forks} -C ${range_multiplier})
        echo "Current range is: \$current_range_pages"
        """
}

process ocrd_cis_ocropy_binarize_0 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-cis-ocropy-binarize -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group}
        """
}

process ocrd_anybaseocr_crop_1 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-anybaseocr-crop -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group}
        """
}

process ocrd_skimage_binarize_2 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-skimage-binarize -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group} -p '{"method": "li"}'
        """
}

process ocrd_skimage_denoise_3 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-skimage-denoise -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group} -p '{"level-of-operation": "page"}'
        """
}

process ocrd_tesserocr_deskew_4 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-tesserocr-deskew -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group} -p '{"operation_level": "page"}'
        """
}

process ocrd_cis_ocropy_segment_5 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-cis-ocropy-segment -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group} -p '{"level-of-operation": "page"}'
        """
}

process ocrd_cis_ocropy_dewarp_6 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-cis-ocropy-dewarp -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group}
        """
}

process ocrd_calamari_recognize_7 {
    debug true
    maxForks params.forks
    cpus params.cpus_per_fork
    memory params.ram_per_fork

    input:
        val mets_path
        val page_range
        val workspace_dir
        val input_group
        val output_group

    output:
        val mets_path
        val page_range
        val workspace_dir

    script:
        """
        ${params.env_wrapper_cmd} ocrd-calamari-recognize -w ${workspace_dir} -m ${mets_path} -I ${input_group} -O ${output_group} -p '{"checkpoint_dir": "qurator-gt4histocr-1.0"}'
        """
}

workflow {
    main:
        ch_range_multipliers = Channel.of(0..params.forks.intValue()-1)
        split_page_ranges(ch_range_multipliers)
        ocrd_cis_ocropy_binarize_0(split_page_ranges.out[0], split_page_ranges.out[1], params.workspace_dir, params.input_file_group "OCR-D-BIN")
        ocrd_anybaseocr_crop_1(ocrd_cis_ocropy_binarize_0.out[0], ocrd_cis_ocropy_binarize_0.out[1], ocrd_cis_ocropy_binarize_0.out[2], "OCR-D-BIN", "OCR-D-CROP")
        ocrd_skimage_binarize_2(ocrd_anybaseocr_crop_1.out[0], ocrd_anybaseocr_crop_1.out[1], ocrd_anybaseocr_crop_1.out[2], "OCR-D-CROP", "OCR-D-BIN2")
        ocrd_skimage_denoise_3(ocrd_skimage_binarize_2.out[0], ocrd_skimage_binarize_2.out[1], ocrd_skimage_binarize_2.out[2], "OCR-D-BIN2", "OCR-D-BIN-DENOISE")
        ocrd_tesserocr_deskew_4(ocrd_skimage_denoise_3.out[0], ocrd_skimage_denoise_3.out[1], ocrd_skimage_denoise_3.out[2], "OCR-D-BIN-DENOISE", "OCR-D-BIN-DENOISE-DESKEW")
        ocrd_cis_ocropy_segment_5(ocrd_tesserocr_deskew_4.out[0], ocrd_tesserocr_deskew_4.out[1], ocrd_tesserocr_deskew_4.out[2], "OCR-D-BIN-DENOISE-DESKEW", "OCR-D-SEG")
        ocrd_cis_ocropy_dewarp_6(ocrd_cis_ocropy_segment_5.out[0], ocrd_cis_ocropy_segment_5.out[1], ocrd_cis_ocropy_segment_5.out[2], "OCR-D-SEG", "OCR-D-SEG-LINE-RESEG-DEWARP")
        ocrd_calamari_recognize_7(ocrd_cis_ocropy_dewarp_6.out[0], ocrd_cis_ocropy_dewarp_6.out[1], ocrd_cis_ocropy_dewarp_6.out[2], "OCR-D-SEG-LINE-RESEG-DEWARP", "OCR-D-OCR")
}
