// This workflow was automatically generated by the v2.17.0 operandi_utils.oton module
nextflow.enable.dsl = 2

params.input_file_group = "OCR-D-IMG"
params.mets_path = "null"
params.workspace_dir = "null"

process ocrd_olena_binarize_0 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-olena-binarize -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"impl": "sauvola"}'
        """
}

process ocrd_anybaseocr_crop_1 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-anybaseocr-crop -m ${mets_file} -I ${input_file_group} -O ${output_file_group}
        """
}

process ocrd_olena_binarize_2 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-olena-binarize -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"impl": "kim"}'
        """
}

process ocrd_cis_ocropy_denoise_3 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-cis-ocropy-denoise -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"level-of-operation": "page"}'
        """
}

process ocrd_cis_ocropy_deskew_4 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-cis-ocropy-deskew -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"level-of-operation": "page"}'
        """
}

process ocrd_tesserocr_segment_region_5 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-tesserocr-segment-region -m ${mets_file} -I ${input_file_group} -O ${output_file_group}
        """
}

process ocrd_segment_repair_6 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-segment-repair -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"plausibilize": true}'
        """
}

process ocrd_cis_ocropy_deskew_7 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-cis-ocropy-deskew -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"level-of-operation": "region"}'
        """
}

process ocrd_cis_ocropy_clip_8 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-cis-ocropy-clip -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"level-of-operation": "region"}'
        """
}

process ocrd_tesserocr_segment_line_9 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-tesserocr-segment-line -m ${mets_file} -I ${input_file_group} -O ${output_file_group}
        """
}

process ocrd_segment_repair_10 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-segment-repair -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"sanitize": true}'
        """
}

process ocrd_cis_ocropy_dewarp_11 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-cis-ocropy-dewarp -m ${mets_file} -I ${input_file_group} -O ${output_file_group}
        """
}

process ocrd_calamari_recognize_12 {
    maxForks 1

    input:
        path mets_file
        val input_file_group
        val output_file_group

    output:
        path mets_file

    script:
        """
        ocrd-calamari-recognize -m ${mets_file} -I ${input_file_group} -O ${output_file_group} -p '{"checkpoint_dir": "qurator-gt4histocr-1.0"}'
        """
}

workflow {
    main:
        ocrd_olena_binarize_0(params.mets_path, params.input_file_group, "OCR-D-BIN")
        ocrd_anybaseocr_crop_1(ocrd_olena_binarize_0.out, "OCR-D-BIN", "OCR-D-CROP")
        ocrd_olena_binarize_2(ocrd_anybaseocr_crop_1.out, "OCR-D-CROP", "OCR-D-BIN2")
        ocrd_cis_ocropy_denoise_3(ocrd_olena_binarize_2.out, "OCR-D-BIN2", "OCR-D-BIN-DENOISE")
        ocrd_cis_ocropy_deskew_4(ocrd_cis_ocropy_denoise_3.out, "OCR-D-BIN-DENOISE", "OCR-D-BIN-DENOISE-DESKEW")
        ocrd_tesserocr_segment_region_5(ocrd_cis_ocropy_deskew_4.out, "OCR-D-BIN-DENOISE-DESKEW", "OCR-D-SEG-REG")
        ocrd_segment_repair_6(ocrd_tesserocr_segment_region_5.out, "OCR-D-SEG-REG", "OCR-D-SEG-REPAIR")
        ocrd_cis_ocropy_deskew_7(ocrd_segment_repair_6.out, "OCR-D-SEG-REPAIR", "OCR-D-SEG-REG-DESKEW")
        ocrd_cis_ocropy_clip_8(ocrd_cis_ocropy_deskew_7.out, "OCR-D-SEG-REG-DESKEW", "OCR-D-SEG-REG-DESKEW-CLIP")
        ocrd_tesserocr_segment_line_9(ocrd_cis_ocropy_clip_8.out, "OCR-D-SEG-REG-DESKEW-CLIP", "OCR-D-SEG-LINE")
        ocrd_segment_repair_10(ocrd_tesserocr_segment_line_9.out, "OCR-D-SEG-LINE", "OCR-D-SEG-REPAIR-LINE")
        ocrd_cis_ocropy_dewarp_11(ocrd_segment_repair_10.out, "OCR-D-SEG-REPAIR-LINE", "OCR-D-SEG-LINE-RESEG-DEWARP")
        ocrd_calamari_recognize_12(ocrd_cis_ocropy_dewarp_11.out, "OCR-D-SEG-LINE-RESEG-DEWARP", "OCR-D-OCR")
}
