FROM ubuntu:22.04

LABEL org.opencontainers.image.authors="DFG OCR-D OPERANDI Project"
LABEL version="0.1"
LABEL description="This Dockerfile builds the OPERANDI Server.\
The OPERANDI Server establishes a Service endpoint for batch requests and also for processing on demand, it accepts job requests and enqueues these job descriptions to the message queue of another service, the OPERANDI Broker Service.\
see https://github.com/subugoe/operandi"
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONIOENCODING utf8
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY ./operandi_server/ /usr/src/operandi_server
COPY ./rabbit_mq_utils/ /usr/src/rabbit_mq_utils

WORKDIR /usr/src/operandi_server/operandi_server

# install dependencies    
RUN apt-get update && apt-get -y install \
    git \
    curl \
    git  \
    make \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    sudo \
    time \
    wget  

RUN python3 -m pip install --upgrade pip setuptools
RUN pip3 install -U pip wheel
RUN python3 -m pip install -r /usr/src/operandi_server/requirements.txt
RUN pip3 install /usr/src/operandi_server
RUN python3 -m pip install -r /usr/src/rabbit_mq_utils/requirements.txt
RUN pip3 install /usr/src/rabbit_mq_utils

EXPOSE 8000

RUN echo "Operandi server build success"
