FROM ubuntu:22.04

MAINTAINER OPERANDI
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONIOENCODING utf8
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY ./operandi_server/ /usr/src/operandi_server

WORKDIR /usr/src/operandi_server/operandi_server

# install dependencies    
RUN apt-get update && apt-get -y install \
    git \
    curl \
    git  \
    make \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    sudo \
    time \
    wget  

RUN python3 -m pip install --upgrade pip setuptools
RUN pip3 install -U pip wheel
RUN python3 -m pip install -r /usr/src/operandi_server/requirements.txt
RUN pip3 install /usr/src/operandi_server

EXPOSE 8000

RUN echo "Operandi server build success"
