FROM ubuntu:22.04

MAINTAINER OPERANDI
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONIOENCODING utf8
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY ./service_broker/ /usr/src/service_broker

WORKDIR /usr/src/service_broker/service_broker

# install dependencies    
RUN apt-get update && apt-get -y install \
    git \
    curl \
    git  \
    libmagic-dev \
    make \
    openjdk-11-jdk \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    software-properties-common \
    sudo \
    time \
    wget \
    apt-transport-https \
    gnupg-agent \
    ca-certificates

# Install Docker
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
RUN apt install docker-ce docker-ce-cli containerd.io -y

# Install Nextflow
RUN wget -qO- https://get.nextflow.io | bash
RUN chmod +x nextflow
RUN mv nextflow /usr/local/bin/

RUN python3 -m pip install --upgrade pip setuptools
RUN pip3 install -U pip wheel
RUN python3 -m pip install -r /usr/src/service_broker/requirements.txt
RUN pip3 install /usr/src/service_broker

RUN echo "Operandi broker build success"
